#!/bin/bash

#SBATCH --time=20:29:59
#SBATCH --partition=regular
#SBATCH --mem=60GB
#SBATCH --cpus-per-task=1

ml Python/3.6.4-foss-2018a

source ../venv/bin/activate

python3 -u cross_validation_for_al_mf.py 0.1
python3 -u cross_validation_for_al_mf.py 0.3
python3 -u cross_validation_for_al_mf.py 0.5
python3 -u cross_validation_for_al_mf.py 0.7
python3 -u cross_validation_for_al_mf.py 0.9
python3 -u cross_validation_for_al_mf.py 1
