#!/bin/bash

#SBATCH --time=23:55:00
#SBATCH --partition=regular
#SBATCH --mem=100GB
#SBATCH --cpus-per-task=4

ml Python/3.6.4-foss-2018a

source ../venv/bin/activate

python3 -u final_mf_vfh_and_all_image_features.py
