#!/bin/bash

#SBATCH --time=23:55:00
#SBATCH --partition=short
#SBATCH --mem=120GB
#SBATCH --cpus-per-task=1

ml Python/3.6.4-foss-2018a

source ../venv/bin/activate

python3 -u cross_validation_for_al_mf.py
